name: common_workflow
on:
  push:
    branches:
      - main

#--------------------------------------------------------- UPDATE MANIFEST FILES WITH COMMIT HASHES -----------------------------------------------------------------
jobs:
  Change_dev_manifest_with_commit_hash:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: echo WE are running ACR............................
